name: DEV Test Build

on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - name: 拉取仓库
        uses: actions/checkout@v4

      - name: 获取版本
        shell: powershell
        run: |
          $version = (Get-Content package.json | ConvertFrom-Json).version
          echo "PACKAGE_VERSION=$version" >> $env:GITHUB_ENV

      - name: 安装Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 安装 UPX
        shell: powershell
        run: choco install upx --no-progress

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install imageio
          pip install -r requirements.txt
          pip install pyinstaller

      - name: 编译
        run: |
          pyinstaller --onefile --distpath build --name "Onekey_v${{ env.PACKAGE_VERSION }}" --icon "icon.jpg" --add-data "web;web" --add-data "icon.jpg;." --upx-exclude=vcruntime140.dll --upx-exclude=python311.dll main.py

      - name: 上传包
        uses: actions/upload-artifact@v4
        with:
          name: Onekey_v${{ env.PACKAGE_VERSION }}.exe
          path: build/Onekey_v${{ env.PACKAGE_VERSION }}.exe